---
- name: Install Bash
  become: yes
  pacman:
    name:
      - bash
      - bash-completion
    state: present
  tags:
    - shell

- name: Install Fish
  become: yes
  pacman:
    name:
      - fish
    state: present
  tags:
    - shell
