---
- name: Install OpenSSH
  become: yes
  pacman:
    name: openssh
    state: present

- name: Push OpenSSH daemon configuration file
  become: yes
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config

- name: Create OpenSSH systemd unit file directory
  file:
    path: /etc/systemd/system/sshd.socket.d
    state: directory

- name: Push OpenSSH socket unit file
  become: yes
  template:
    src: sshd-socket-override.conf.j2
    dest: /etc/systemd/system/sshd.socket.d/override.conf
  notify:
    - reload systemd config
    - restart sshd

- name: Enable and start OpenSSH
  become: yes
  service:
    name: sshd.socket
    enabled: yes
    state: started
  when: ssh.enable_sshd is defined and ssh.enable_sshd == True

- name: Disable and stop OpenSSH
  become: yes
  service:
    name: sshd.socket
    enabled: no
    state: stopped
  when: ssh.enable_sshd is defined and ssh.enable_sshd == True

- name: Install sshfs
  become: yes
  pacman:
    name: sshfs
    state: present

- name: Install autossh
  become: yes
  pacman:
    name: autossh
    state: present

- name: Copy fuse configuration file
  become: yes
  copy:
    src: fuse.conf
    dest: /etc/fuse.conf

- name: Install keychain
  become: yes
  pacman:
    name: keychain
    state: present

- name: Install x11-ask-pass
  become: yes
  pacman:
    name: x11-ssh-askpass
    state: present

- name: Export SSH_ASKPASS environment variable
  become: yes
  lineinfile:
    dest: /etc/profile
    state: present
    line: 'export SSH_ASKPASS: "/usr/lib/ssh/x11-ssh-askpass"'

- name: Make directory for user SSH key
  file:
    path: /home/{{ user.name }}/.ssh
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: Install user SSH key
  copy:
    src: "{{ ssh.user_key }}"
    dest: /home/{{ user.name }}/.ssh/id_rsa
    mode: 600
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
  when: ssh.user_key is defined

- name: Install Mosh
  become: yes
  pacman:
    name: mosh
    state: present
