---
- include: inkscape.yml
- include: gimp.yml
- include: gthumb.yml
- include: imv.yml

- name: Install misc media codecs and helpers
  become: yes
  pacman:
    name:
      - flac
      - lame
      - gst-libav
      - gst-plugins-good
      - exiv2
      - perl-image-exiftool
      - opus-tools
    state: present

- name: Install Metadata Anonymisation Toolkit
  aur:
    name: mat2
    user: "{{ user.name }}"
    skip_pgp: yes
  tags:
    - aur
    - mat

- name: Install youtube-dl
  become: yes
  pacman:
    name: youtube-dl
    state: present

- name: Install zbar
  become: yes
  pacman:
    name: zbar
    state: present

- name: Install sxiv
  become: yes
  pacman:
    name: sxiv
    state: present

- name: Install svgcleaner
  become: yes
  pacman:
    name: svgcleaner
    state: present
